image: node:10

stages:
  - lint
  - test
  - build
  - publish

before_script:
  - echo $NPMJS_AUTH_TOKEN > .npmrc
  - npm ci

Lint sources:
  stage: lint
  script:
    - npm run lint

.Run tests:
  stage: test
  script:
    - npm test

Build Package:
  stage: build
  script:
    - npm run build

Publish Package:
  stage: publish
  only: ['tags']
  script:
    - npm run build
    - npm publish
