image: node:10.15

stages:
  - test
  - publish

before_script:
  - echo $NPMJS_AUTH_TOKEN >> .npmrc
  - npm ci

Checking sources:
  stage: test
  script:
    - npm run lint
    - npm run build

Publish SDK:
  stage: publish
  only: ['tags']
  script:
    - npm run build
    - npm publish
