image: node:10.4

stages:
  - lint
  - test
  - build
  - publish
  - documentation

before_script:
  - echo $NPMJS_AUTH_TOKEN >> .npmrc
  - npm ci

Lint sources:
  stage: lint
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm test

Build SDK:
  stage: build
  script:
    - npm run build

Publish SDK:
  stage: publish
  only: ['tags']
  script:
    - npm run build
    - npm publish
